import { useEffect, useState } from 'react';
import { RefreshCw, Globe2, Info } from 'lucide-react';
import { api, type DailyReview as DR } from '../lib/api';
import { TalkingPoints } from './TalkingPoints';

export function DailyReview() {
  const [data, setData] = useState<DR | null>(null);
  const [err, setErr] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const load = (refresh = false) => {
    setBusy(true);
    setErr(null);
    (refresh ? api.refreshReview() : api.dailyReview())
      .then(setData)
      .catch((e) => setErr(String(e.message)))
      .finally(() => setBusy(false));
  };

  useEffect(() => load(false), []);

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold">Daily market brief</h2>
        <button className="btn-ghost" onClick={() => load(true)} disabled={busy}>
          <RefreshCw size={15} className={busy ? 'animate-spin' : ''} /> Refresh
        </button>
      </div>

      {err && <p className="text-sm text-up">Couldn’t load the brief: {err}</p>}
      {!data && !err && <p className="text-sm text-brand-muted">Loading…</p>}

      {data && (
        <>
          {!data.configured && (
            <div className="card p-3 flex gap-2 items-start bg-amber-50 border-amber-200">
              <Info size={16} className="text-amber-600 mt-0.5 shrink-0" />
              <p className="text-sm text-amber-800">{data.note}</p>
            </div>
          )}

          <section className="card p-5">
            <p className="text-[15px] leading-relaxed whitespace-pre-line">{data.review}</p>
            {data.provider && (
              <p className="label mt-3">
                Generated by {data.provider} · {new Date(data.asOf).toLocaleString('en-GB')}
              </p>
            )}
          </section>

          {data.talkingPoints.length > 0 && (
            <section>
              <h3 className="label mb-2">Talking points</h3>
              <TalkingPoints points={data.talkingPoints} />
            </section>
          )}

          {data.geoHooks.length > 0 && (
            <section>
              <h3 className="label mb-2">Geopolitical angles</h3>
              <ul className="space-y-2">
                {data.geoHooks.map((g, i) => (
                  <li key={i} className="card p-3 flex items-start gap-3">
                    <Globe2 size={16} className="text-brand-green mt-0.5 shrink-0" />
                    <div>
                      <div className="text-sm font-medium">{g.headline}</div>
                      <div className="text-sm text-brand-muted">{g.angle}</div>
                    </div>
                  </li>
                ))}
              </ul>
            </section>
          )}
        </>
      )}
    </div>
  );
}
